export const SAMPLE_PRODUCTS = [
  {
    "id": "sample-1",
    "name": "Mango Avakaya Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 170,
    "offerPrice": 140,
    "imageUrl": "product-photos/mango-pickle.jpg",
    "description": "Traditional homemade mango avakaya pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-2",
    "name": "Tomato Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 150,
    "offerPrice": 120,
    "imageUrl": "product-photos/tomato-pickle.jpg",
    "description": "Traditional homemade tomato pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-3",
    "name": "Gongura Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 165,
    "offerPrice": 135,
    "imageUrl": "product-photos/gongura-pickle.jpg",
    "description": "Traditional homemade gongura pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-4",
    "name": "Lemon Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 150,
    "offerPrice": 120,
    "imageUrl": "product-photos/lemon-pickle.jpg",
    "description": "Traditional homemade lemon pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-5",
    "name": "Garlic Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 180,
    "offerPrice": 150,
    "imageUrl": "product-photos/pickle-selection.jpg",
    "description": "Traditional homemade garlic pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-6",
    "name": "Amla Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 160,
    "offerPrice": 130,
    "imageUrl": "product-photos/pickle-selection.jpg",
    "description": "Traditional homemade amla pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-7",
    "name": "Green Chilli Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 160,
    "offerPrice": 130,
    "imageUrl": "product-photos/pickle-selection.jpg",
    "description": "Traditional homemade green chilli pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-8",
    "name": "Mixed Vegetable Pickle",
    "category": "Pickles",
    "weight": "500 g",
    "mrp": 170,
    "offerPrice": 140,
    "imageUrl": "product-photos/pickle-selection.jpg",
    "description": "Traditional homemade mixed vegetable pickle prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-9",
    "name": "Janthikalu",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 130,
    "offerPrice": 110,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade janthikalu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-10",
    "name": "Chekkalu",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 130,
    "offerPrice": 110,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade chekkalu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-11",
    "name": "Murukku",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 130,
    "offerPrice": 110,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade murukku prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-12",
    "name": "Ribbon Pakoda",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 140,
    "offerPrice": 115,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade ribbon pakoda prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-13",
    "name": "Boondi Mixture",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 125,
    "offerPrice": 100,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade boondi mixture prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-14",
    "name": "Kara Sev",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 130,
    "offerPrice": 105,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade kara sev prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-15",
    "name": "Masala Peanuts",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 120,
    "offerPrice": 95,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade masala peanuts prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-16",
    "name": "Banana Chips",
    "category": "Snacks",
    "weight": "250 g",
    "mrp": 135,
    "offerPrice": 110,
    "imageUrl": "product-photos/murukku.jpg",
    "description": "Traditional homemade banana chips prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-17",
    "name": "Ariselu",
    "category": "Sweets",
    "weight": "500 g",
    "mrp": 210,
    "offerPrice": 180,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade ariselu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-18",
    "name": "Sunnundalu",
    "category": "Sweets",
    "weight": "500 g",
    "mrp": 220,
    "offerPrice": 190,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade sunnundalu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-19",
    "name": "Boondi Laddu",
    "category": "Sweets",
    "weight": "500 g",
    "mrp": 200,
    "offerPrice": 170,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade boondi laddu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-20",
    "name": "Rava Laddu",
    "category": "Sweets",
    "weight": "500 g",
    "mrp": 195,
    "offerPrice": 165,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade rava laddu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-21",
    "name": "Mysore Pak",
    "category": "Sweets",
    "weight": "500 g",
    "mrp": 240,
    "offerPrice": 210,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade mysore pak prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-22",
    "name": "Gavvalu",
    "category": "Sweets",
    "weight": "500 g",
    "mrp": 180,
    "offerPrice": 150,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade gavvalu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-23",
    "name": "Kajjikayalu",
    "category": "Sweets",
    "weight": "500 g",
    "mrp": 210,
    "offerPrice": 180,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade kajjikayalu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-24",
    "name": "Bobbatlu",
    "category": "Sweets",
    "weight": "6 pieces",
    "mrp": 190,
    "offerPrice": 160,
    "imageUrl": "product-photos/laddu.jpg",
    "description": "Traditional homemade bobbatlu prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-25",
    "name": "Peanut Chikki",
    "category": "Chikkis",
    "weight": "250 g",
    "mrp": 110,
    "offerPrice": 90,
    "imageUrl": "product-photos/chikki.jpg",
    "description": "Traditional homemade peanut chikki prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-26",
    "name": "Sesame Chikki",
    "category": "Chikkis",
    "weight": "250 g",
    "mrp": 120,
    "offerPrice": 100,
    "imageUrl": "product-photos/chikki.jpg",
    "description": "Traditional homemade sesame chikki prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-27",
    "name": "Dry Fruit Chikki",
    "category": "Chikkis",
    "weight": "250 g",
    "mrp": 210,
    "offerPrice": 180,
    "imageUrl": "product-photos/chikki.jpg",
    "description": "Traditional homemade dry fruit chikki prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-28",
    "name": "Coconut Chikki",
    "category": "Chikkis",
    "weight": "250 g",
    "mrp": 135,
    "offerPrice": 110,
    "imageUrl": "product-photos/chikki.jpg",
    "description": "Traditional homemade coconut chikki prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-29",
    "name": "Karam Podi",
    "category": "Powders",
    "weight": "200 g",
    "mrp": 110,
    "offerPrice": 90,
    "imageUrl": "product-photos/powder.jpg",
    "description": "Traditional homemade karam podi prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-30",
    "name": "Idli Podi",
    "category": "Powders",
    "weight": "200 g",
    "mrp": 110,
    "offerPrice": 90,
    "imageUrl": "product-photos/powder.jpg",
    "description": "Traditional homemade idli podi prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-31",
    "name": "Curry Leaf Powder",
    "category": "Powders",
    "weight": "200 g",
    "mrp": 120,
    "offerPrice": 100,
    "imageUrl": "product-photos/powder.jpg",
    "description": "Traditional homemade curry leaf powder prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-32",
    "name": "Flaxseed Powder",
    "category": "Powders",
    "weight": "200 g",
    "mrp": 125,
    "offerPrice": 105,
    "imageUrl": "product-photos/powder.jpg",
    "description": "Traditional homemade flaxseed powder prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-33",
    "name": "Peanut Powder",
    "category": "Powders",
    "weight": "200 g",
    "mrp": 115,
    "offerPrice": 95,
    "imageUrl": "product-photos/powder.jpg",
    "description": "Traditional homemade peanut powder prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-34",
    "name": "Sambar Powder",
    "category": "Powders",
    "weight": "200 g",
    "mrp": 110,
    "offerPrice": 90,
    "imageUrl": "product-photos/powder.jpg",
    "description": "Traditional homemade sambar powder prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-35",
    "name": "Rasam Powder",
    "category": "Powders",
    "weight": "200 g",
    "mrp": 110,
    "offerPrice": 90,
    "imageUrl": "product-photos/powder.jpg",
    "description": "Traditional homemade rasam powder prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-36",
    "name": "Pulihora Mix",
    "category": "Instant Mixes",
    "weight": "250 g",
    "mrp": 120,
    "offerPrice": 100,
    "imageUrl": "product-photos/instant-mix.jpg",
    "description": "Traditional homemade pulihora mix prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-37",
    "name": "Vangibath Mix",
    "category": "Instant Mixes",
    "weight": "250 g",
    "mrp": 125,
    "offerPrice": 105,
    "imageUrl": "product-photos/instant-mix.jpg",
    "description": "Traditional homemade vangibath mix prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-38",
    "name": "Bisibele Bath Mix",
    "category": "Instant Mixes",
    "weight": "250 g",
    "mrp": 130,
    "offerPrice": 110,
    "imageUrl": "product-photos/instant-mix.jpg",
    "description": "Traditional homemade bisibele bath mix prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-39",
    "name": "Lemon Rice Mix",
    "category": "Instant Mixes",
    "weight": "250 g",
    "mrp": 120,
    "offerPrice": 100,
    "imageUrl": "product-photos/instant-mix.jpg",
    "description": "Traditional homemade lemon rice mix prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  },
  {
    "id": "sample-40",
    "name": "Tamarind Rice Mix",
    "category": "Instant Mixes",
    "weight": "250 g",
    "mrp": 125,
    "offerPrice": 105,
    "imageUrl": "product-photos/instant-mix.jpg",
    "description": "Traditional homemade tamarind rice mix prepared with carefully selected ingredients.",
    "inStock": true,
    "isSample": true
  }
];
